name: hello-world
on: push
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.14.2'
      - name: Install node modules
        run: npm i
      - name: Build the project
        run: npm run build
      - name: setup finish
        run: echo hurray!
